### ISSUE TITLE
Development - more reliable feature specs

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1116]
### Descriptive summary

Revise some feature specs for more reliable results, e.g. see
- https://tech.greenhouse.io/2015/10/07/effectively-debugging-capybara-feature-specs.html

**Comment by darrenleeweber** [comment]
For example, an intermittent failure is:
```
  1) Batch management of works editing and viewing multiple works edits each field and displays the changes

     Failure/Error: expect(page).to have_content 'Changes Saved', wait: Capybara.default_max_wait_time * 5

       expected to find text "Changes Saved" in "Date Created Date Created The date on which the work was created. Add another Date Created Cancel"

     # ./spec/features/batch_edit_spec.rb:124:in `block in fill_in_field_wait'
     # ./spec/features/batch_edit_spec.rb:123:in `fill_in_field_wait'
     # ./spec/features/batch_edit_spec.rb:25:in `block (4 levels) in <top (required)>'
     # ./spec/features/batch_edit_spec.rb:25:in `each'
     # ./spec/features/batch_edit_spec.rb:25:in `block (3 levels) in <top (required)>'
```

**Comment by mjgiarlo** [comment]
@darrenleeweber Yep, that is the known flapper. I started taking this on in #989 if you or someone else wanted to pick this up to take on the flapper head-on.
