### ISSUE TITLE
Embargo/Lease controllers to consolidate behavior concerns

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1122]
### Descriptive summary

I tried to apply a similar change to the work in #1041 for embargo/lease controllers in https://github.com/samvera-labs/hyrax/pull/1042, but it broke specs in various ways.  It may be easier to consolidate this change in #1041 or another PR.

**Comment by darrenleeweber** [comment]
Simply moving the module-body of the embargo and lease behavior concerns into the controller body does not work, it results in the following 12 spec failures on #1042 
```
Failures:

  1) Hyrax::EmbargoesController#destroy when I do not have edit permissions for the object denies access
     Failure/Error: Hyrax::Actors::EmbargoActor.new(curation_concern).destroy
     
     NameError:
       undefined local variable or method `curation_concern' for #<Hyrax::EmbargoesController:0x0055cd1a697840>
     # ./app/controllers/hyrax/embargoes_controller.rb:13:in `destroy'
     # ./spec/controllers/hyrax/embargoes_controller_spec.rb:43:in `block (4 levels) in <top (required)>'

  2) Hyrax::EmbargoesController#destroy when I have permission to edit the object that has files deactivates embargo and checks to see if we want to copy the visibility to files
     Failure/Error: Hyrax::Actors::EmbargoActor.new(curation_concern).destroy
     
     NameError:
       undefined local variable or method `curation_concern' for #<Hyrax::EmbargoesController:0x0055cd18b31bf0>
     # ./app/controllers/hyrax/embargoes_controller.rb:13:in `destroy'
     # ./spec/controllers/hyrax/embargoes_controller_spec.rb:71:in `block (5 levels) in <top (required)>'

  3) Hyrax::EmbargoesController#destroy when I have permission to edit the object that has no files deactivates embargo and redirects
     Failure/Error: Hyrax::Actors::EmbargoActor.new(curation_concern).destroy
     
     NameError:
       undefined local variable or method `curation_concern' for #<Hyrax::EmbargoesController:0x0055cd1b10bce0>
     # ./app/controllers/hyrax/embargoes_controller.rb:13:in `destroy'
     # ./spec/controllers/hyrax/embargoes_controller_spec.rb:58:in `block (5 levels) in <top (required)>'

  4) Hyrax::EmbargoesController#edit when I do not have edit permissions for the object redirects
     Failure/Error: expect(response.status).to eq 302
     
       expected: 302
            got: 200
     
       (compared using ==)
     # ./spec/controllers/hyrax/embargoes_controller_spec.rb:28:in `block (4 levels) in <top (required)>'

  5) Hyrax::EmbargoesController#index when I am a repository manager shows me the page
     Failure/Error: get :index
     
     ActionController::UnknownFormat:
       Hyrax::EmbargoesController#index is missing a template for this request format and variant.
     
       request.formats: ["text/html"]
       request.variant: []
     
       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
     # ./spec/controllers/hyrax/embargoes_controller_spec.rb:18:in `block (4 levels) in <top (required)>'

  6) leases managing leases shows lists of objects under lease
     Failure/Error: visit '/leases'
     
     ActionController::UnknownFormat:
       Hyrax::LeasesController#index is missing a template for this request format and variant.
     
       request.formats: ["text/html"]
       request.variant: []
     
       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
     # ./spec/features/lease_spec.rb:41:in `block (3 levels) in <top (required)>'

  7) Hyrax::LeasesController#edit when I do not have edit permissions for the object redirects
     Failure/Error: expect(response.status).to eq 302
     
       expected: 302
            got: 200
     
       (compared using ==)
     # ./spec/controllers/hyrax/leases_controller_spec.rb:28:in `block (4 levels) in <top (required)>'

  8) Hyrax::LeasesController#index when I am a repository manager shows me the page
     Failure/Error: get :index
     
     ActionController::UnknownFormat:
       Hyrax::LeasesController#index is missing a template for this request format and variant.
     
       request.formats: ["text/html"]
       request.variant: []
     
       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
     # ./spec/controllers/hyrax/leases_controller_spec.rb:18:in `block (4 levels) in <top (required)>'

  9) Hyrax::LeasesController#destroy when I do not have edit permissions for the object denies access
     Failure/Error: Hyrax::Actors::LeaseActor.new(curation_concern).destroy
     
     NameError:
       undefined local variable or method `curation_concern' for #<Hyrax::LeasesController:0x0055cd187f6d78>
     # ./app/controllers/hyrax/leases_controller.rb:13:in `destroy'
     # ./spec/controllers/hyrax/leases_controller_spec.rb:43:in `block (4 levels) in <top (required)>'

  10) Hyrax::LeasesController#destroy when I have permission to edit the object that has no files deactivates the lease and redirects
      Failure/Error: Hyrax::Actors::LeaseActor.new(curation_concern).destroy
      
      NameError:
        undefined local variable or method `curation_concern' for #<Hyrax::LeasesController:0x0055cd164b4b80>
      # ./app/controllers/hyrax/leases_controller.rb:13:in `destroy'
      # ./spec/controllers/hyrax/leases_controller_spec.rb:57:in `block (5 levels) in <top (required)>'

  11) Hyrax::LeasesController#destroy when I have permission to edit the object with files deactivates the lease and redirects
      Failure/Error: Hyrax::Actors::LeaseActor.new(curation_concern).destroy
      
      NameError:
        undefined local variable or method `curation_concern' for #<Hyrax::LeasesController:0x0055cd1457b778>
      # ./app/controllers/hyrax/leases_controller.rb:13:in `destroy'
      # ./spec/controllers/hyrax/leases_controller_spec.rb:70:in `block (5 levels) in <top (required)>'

  12) embargo managing embargoes shows lists of objects under lease
      Failure/Error: visit '/embargoes'
      
      ActionController::UnknownFormat:
        Hyrax::EmbargoesController#index is missing a template for this request format and variant.
      
        request.formats: ["text/html"]
        request.variant: []
      
        NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
      # ./spec/features/embargo_spec.rb:44:in `block (3 levels) in <top (required)>'
```
