### ISSUE TITLE
`AttachFilesToWorkJob` fails with `A copy of Hyrax::Lockable has been removed from the module tree but is still active!`

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#1307]
### Descriptive summary

In Hyrax 1.0.1, when I attempt to attach a file to a work via `AttachFilesToWorkJob` it fails with the error `A copy of Hyrax::Lockable has been removed from the module tree but is still active!`

### Rationale

I need to import legacy data into Hyrax and have it go through the same processing that works uploaded through the UI go through.

### Steps to reproduce the behavior

1. In the rails console, make a hyrax work:
`etd = FactoryGirl.create(:etd)`
1. Make a `Hyrax::UploadedFile` object with a file attached:
`uf = Hyrax::UploadedFile.create(file: File.open("#{::Rails.root}/spec/fixtures/joey/joey_thesis.pdf"))`
1. Attach the `Hyrax::UploadedFile` object to the work:
`AttachFilesToWorkJob.perform_now(a, [uf])`

It starts to work, makes it through a few jobs, then fails:

```ruby
ArgumentError: A copy of Hyrax::Lockable has been removed from the module tree but is still active!
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:496:in `load_missing_constant'
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:203:in `const_missing'
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.1/app/services/hyrax/lockable.rb:10:in `lock_manager'
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.1/app/services/hyrax/lockable.rb:6:in `acquire_lock_for'
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.1/app/actors/hyrax/actors/file_set_actor.rb:45:in `attach_file_to_work'
	from /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.1/app/jobs/attach_files_to_work_job.rb:14:in `block in perform'
```

**Comment by jcoyne** [comment]
Sounds like an autoload problem. Are you running with  `config.cache_classes=true` (this is default with `RAILS_ENV=production`) that might clear it up.

**Comment by mjgiarlo** [comment]
@jcoyne @bess Do you suspect this is an issue in `master` as well?

**Comment by jcoyne** [comment]
I have never seen this case before, so I have no idea where it may surface.

**Comment by bess** [comment]
I can't get things to load with `config.cache_classes=true` (I encounter some other problem). I'll try running in production to see if I still see the error.

**Comment by atz** [comment]
The bug is real, but autoloading issues are a pain to debug, sometimes relying on system-dependent filesystem ordering.
