### ISSUE TITLE
Solr Error when visiting Review Submissions tab

### ISSUE THREAD

**Issue by luisgreg99** [samvera/hyrax#1395]
### Descriptive summary

Version: hyrax (2.0.0.alpha)

Traceback:
```
D, [2017-07-26T14:56:45.757860 #35049] DEBUG -- : [f86423ed-5b0e-4801-b922-e02c882889b3] Actionable roles for luisramg are ["default-depositing", "default-managing", "de
fault-depositing", "default-approving", "One Step-depositing"]
I, [2017-07-26T14:56:45.766279 #35049]  INFO -- : [f86423ed-5b0e-4801-b922-e02c882889b3]   Rendered /data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256
/app/views/hyrax/admin/workflows/index.html.erb within layouts/dashboard (231.7ms)
I, [2017-07-26T14:56:45.766578 #35049]  INFO -- : [f86423ed-5b0e-4801-b922-e02c882889b3] Completed 500 Internal Server Error in 242ms (ActiveRecord: 63.1ms)
F, [2017-07-26T14:56:45.768851 #35049] FATAL -- : [f86423ed-5b0e-4801-b922-e02c882889b3]   
F, [2017-07-26T14:56:45.768908 #35049] FATAL -- : [f86423ed-5b0e-4801-b922-e02c882889b3] ActionView::Template::Error (RSolr::Error::Http - 400 Bad Request
Error: 'no field name specified in query and no default specified via \'df\' param','code'=>400}}

URI: http://127.0.0.1:8983/solr/hydra-staging/select?wt=ruby&rows=1000&sort=system_create_dtsi+asc&q=%28_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DArticle%22+OR+_query_
%3A%22%7B%21raw+f%3Dhas_model_ssim%7DGraduateThesisOrDissertation%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DGraduateProject%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_
model_ssim%7DUndergraduateThesisOrProject%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DEescPublication%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DTechnicalRe
port%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DDataset%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DOpenEducationalResource%22+OR+_query_%3A%22%7B%21raw+f%3
Dhas_model_ssim%7DAdministrativeReportOrPublication%22+OR+_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DConferenceProceedingsOrJournal%22+OR+_query_%3A%22%7B%21raw+f%3Dhas
_model_ssim%7DDefault%22%29+AND+%7B%21terms+f%3Dactionable_workflow_roles_ssim%7Ddefault-depositing%2Cdefault-managing%2Cdefault-depositing%2Cdefault-approving%2COne+Ste
p-depositing+AND+-workflow_state_name_ssim%3Adeposited&qt=standard

Backtrace: /data0/hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `get'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/solr_service.rb:44:in `get'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/solr_service.rb:49:in `query'
/data0/hydra/shared/bundle/ruby/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:104:in `search_with_conditions'
/data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:41:in `search_solr'
/data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:34:in `solr_documents'
/data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:18:in `each'
/data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/views/hyrax/admin/workflows/index.html.erb:32:in `__data__hydra_shared_bundle_ruby_______bundler_gems_hyrax____e__a______app_views_hyrax_admin_workflows_index_html_erb__1148288255027944659_70309658394560'):
F, [2017-07-26T14:56:45.769101 #35049] FATAL -- : [f86423ed-5b0e-4801-b922-e02c882889b3]     29:                     </tr>
[f86423ed-5b0e-4801-b922-e02c882889b3]     30:                   </thead>
[f86423ed-5b0e-4801-b922-e02c882889b3]     31:                   <tbody>
[f86423ed-5b0e-4801-b922-e02c882889b3]     32:                     <% @status_list.each do |document| %>
[f86423ed-5b0e-4801-b922-e02c882889b3]     33:                       <tr>
[f86423ed-5b0e-4801-b922-e02c882889b3]     34:                         <td>
[f86423ed-5b0e-4801-b922-e02c882889b3]     35:                           <%= link_to document, [main_app, document] %>
F, [2017-07-26T14:56:45.769159 #35049] FATAL -- : [f86423ed-5b0e-4801-b922-e02c882889b3]   
F, [2017-07-26T14:56:45.769220 #35049] FATAL -- : [f86423ed-5b0e-4801-b922-e02c882889b3] rsolr (1.1.2) lib/rsolr/client.rb:288:in `adapt_response'
[f86423ed-5b0e-4801-b922-e02c882889b3] rsolr (1.1.2) lib/rsolr/client.rb:189:in `execute'
[f86423ed-5b0e-4801-b922-e02c882889b3] rsolr (1.1.2) lib/rsolr/client.rb:175:in `send_and_receive'
[f86423ed-5b0e-4801-b922-e02c882889b3] (eval):2:in `get'
[f86423ed-5b0e-4801-b922-e02c882889b3] active-fedora (11.4.0) lib/active_fedora/solr_service.rb:49:in `query'
[f86423ed-5b0e-4801-b922-e02c882889b3] active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:104:in `search_with_conditions'
[f86423ed-5b0e-4801-b922-e02c882889b3] /data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:41:in `search_solr'
[f86423ed-5b0e-4801-b922-e02c882889b3] /data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:34:in `solr_documents'
[f86423ed-5b0e-4801-b922-e02c882889b3] /data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/services/hyrax/workflow/status_list_service.rb:18:in `each'
[f86423ed-5b0e-4801-b922-e02c882889b3] /data0/hydra/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-848e72a48256/app/views/hyrax/admin/workflows/index.html.erb:32:in `__data__hydra_shared_bundle_ruby_______bundler_gems_hyrax____e__a______app_views_hyrax_admin_workflows_index_html_erb__1148288255027944659_70309658394560'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/template.rb:159:in `block in render'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications.rb:166:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/template.rb:354:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/template.rb:157:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications.rb:164:in `block in instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications.rb:164:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/template_renderer.rb:14:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/renderer/renderer.rb:23:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/rendering.rb:104:in `_render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/streaming.rb:217:in `_render_template'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/rendering.rb:83:in `render_to_body'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/abstract_controller/rendering.rb:26:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/rendering.rb:36:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[f86423ed-5b0e-4801-b922-e02c882889b3] /usr/local/deploy-rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[f86423ed-5b0e-4801-b922-e02c882889b3] activerecord (5.0.4) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/abstract_controller/base.rb:188:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:126:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:455:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:90:in `run_callbacks'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications.rb:164:in `block in instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/notifications.rb:164:in `instrument'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] activerecord (5.0.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/abstract_controller/base.rb:126:in `process'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionview (5.0.4) lib/action_view/rendering.rb:30:in `process'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal.rb:190:in `dispatch'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_controller/metal.rb:262:in `dispatch'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `each'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:725:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/engine.rb:522:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/railtie.rb:193:in `public_send'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/railtie.rb:193:in `method_missing'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `each'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `serve'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:725:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] devise_cas_authenticatable (1.10.1) lib/devise_cas_authenticatable/single_sign_out/rack.rb:14:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[f86423ed-5b0e-4801-b922-e02c882889b3] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[f86423ed-5b0e-4801-b922-e02c882889b3] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/etag.rb:25:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/head.rb:12:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] active-fedora (11.4.0) lib/active_fedora/ldp_cache.rb:26:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/callbacks.rb:90:in `run_callbacks'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/rack/logger.rb:36:in `call_app'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/rack/logger.rb:24:in `block in call'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/rack/logger.rb:24:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] activesupport (5.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] actionpack (5.0.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] railties (5.0.4) lib/rails/engine.rb:522:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] puma (3.9.1) lib/puma/configuration.rb:224:in `call'
[f86423ed-5b0e-4801-b922-e02c882889b3] puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
[f86423ed-5b0e-4801-b922-e02c882889b3] puma (3.9.1) lib/puma/server.rb:435:in `process_client'
[f86423ed-5b0e-4801-b922-e02c882889b3] puma (3.9.1) lib/puma/server.rb:299:in `block in run'
[f86423ed-5b0e-4801-b922-e02c882889b3] puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
### Rationale

When we go to http://localhost:3000/admin/workflows?locale=en we get 500 Internal Server Error:

```
ActionView::Template::Error (RSolr::Error::Http - 400 Bad Request
Error: 'no field name specified in query and no default specified via \'df\' param','code'=>400}}
```

The error appears to happen when there is a work waiting to be reviewed for the user currently logged into the site.

### Expected behavior

When going to the admin/workflows, we expect a page with the list of works waiting to be reviewed for a user with the approving role.

### Actual behavior

A user with the approving role gets `ActionView::Template::Error (RSolr::Error::Http - 400 Bad Request` when going to admin/workflows.

### Steps to reproduce the behavior

1. Create an admin set 'Article'
2. Associate new admin set with a one step mediated deposit workflow (we are using this workflow config https://github.com/osulp/Scholars-Archive/blob/master/config/workflows/one_step.json)
3. Assign the "approving" role to an existing user
4. Have the user with the "approving" role go to the review Review Submissions tab (http://localhost:3000/admin/workflows?locale=en) 
5. User gets `ActionView::Template::Error (RSolr::Error::Http - 400 Bad Request`

**Comment by luisgreg99** [comment]
the error seems to go away if we add the `df=id` param in the query:
`WorkRelation.new.search_with_conditions(query(actionable_roles), {df: 'id', rows: 1000})` at
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/status_list_service.rb#L41

**Comment by mjgiarlo** [comment]
@luisgreg99 Was the traceback above for `user1`, which has the `approving` role? I ask because the first line is:

```
D, [2017-07-26T14:56:45.757860 #35049] DEBUG -- : [f86423ed-5b0e-4801-b922-e02c882889b3] Actionable roles for luisramg are ["default-depositing", "default-managing", "default-depositing", "default-approving", "One Step-depositing"]
```

Which I'd expect to include `"One Step-approving"`, but doesn't. Related?

**Comment by luisgreg99** [comment]
@mjgiarlo yes, it was for `user1`. I was testing with different roles (approving and depositing), thinking that it might have been related to a particular role, but it seems to happen for any role (`One Step-approving` or `One Step-depositing`) assigned to `user1`. I also found that the page renders ok when `user1` has no roles, so it happens when at least one role is assigned to that user (`user1`).

**Comment by straleyb** [comment]
@mjgiarlo So we looked into this a little bit deeper and we can get the solr query to bring back items using `Hyrax::WorkRelation.new.search_with_conditions(query(actionable_roles), {df: 'actionable_workflow_roles', defType: 'edismax', rows: 1000})` in this file: https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/status_list_service.rb#L41 However, it brings back all the works so we had to do a bit of filtering. Either the solr query needs to be fixed or filtering can happen in the `admin/workflows/index.html.erb` or workflows_controller.rb

**Comment by mjgiarlo** [comment]
Thanks for dropping a line, @straleyb! Because there's a bunch of setup required to reproduce the bug, I wonder if anyone would be inclined to craft a test that fails.
