### ISSUE TITLE
file_set_audit_service fails when a file does not have versions

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#1404]
### Descriptive summary

In Hyrax 1.x, the `Hyrax::RepositoryAuditService.audit_everything` service fails when it encounters a file that does not have versions. The error is:
```
NoMethodError: undefined method `each' for #<Hydra::PCDM::File:0x007fcb513bcf80>
/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/activemodel-5.0.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.3/app/services/hyrax/file_set_audit_service.rb:64:in `audit_file'
```
The bug can be fixed by checking to see whether the audit is being run on a file or a version set:
```
[60, 69] in /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.3/app/services/hyrax/file_set_audit_service.rb
   60:       # @param [ActiveFedora::File] file to audit
   61:       # @param [Array] log container for messages
   62:       def audit_file(file, log = [])
   63:         byebug
   64:         versions = file.has_versions? ? file.versions.all : file
=> 65:         versions.each { |v| log << audit_file_version(file.id, v.uri) }
   66:         log
   67:       end
   68:
   69:       # Retrieve or generate the audit check for a file and provide a human-readable status message.
(byebug) versions
#<Hydra::PCDM::File uri="http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf01e" >
(byebug) versions.uri
#<RDF::URI:0x3fd3eaaf2564 URI:http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf01e>
(byebug) audit_file_version(file.id, versions.uri)
#<ChecksumAuditLog id: nil, file_set_id: "5712m6524", file_id: "5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf0...", version: "http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m65...", pass: 999, expected_result: nil, actual_result: nil, created_at: nil, updated_at: nil>
```

**Comment by bess** [comment]
@mjgiarlo I'm confused about why you added this ticket to the 2.0.0 milestone and added a backport needed label. This is for the 1.x branch and it looks like things are pretty different in the 2.x line.

**Comment by mjgiarlo** [comment]
@bess Ah! I meant to undo that. I naïvely added the milestone and label, then did my homework, and then forgot to update this issue. Thanks for the nudge!

**Comment by mjgiarlo** [comment]
I believe #1406 should have closed this issue.
