### ISSUE TITLE
Showing user profile raises "NoMethodError " exception

### ISSUE THREAD

**Issue by paulwalk** [samvera/hyrax#2454]
I have installed a vanilla Hyrax instance using the instructions in the README in this repo.

`rails _5.0.6_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v2.0.1/template.rb`

I have Fedora & Solr running, and have successfully run the recommended rake tasks:
```
rails hyrax:default_admin_set:create
rails generate hyrax:work DataSet
```

I am able to create a new user. When I log in with that user, all seems well until I attempt to go to that user's profile, in my case the URL is:

`http://localhost:3000/dashboard/profiles/paul@paulwalk-dot-net?locale=en`

This raise the exception with these details:
```
/usr/local/bundle/gems/hyrax-2.0.1/app/views/hyrax/users/_vitals.html.erb where line #11 raised:

undefined method `delegated_attributes' for nil:NilClass

Extracted source (around line #28):
def self.delegated_attributes
    primary_concern.delegated_attributes
end

def self.solr_query_handler

Trace of template inclusion: /usr/local/bundle/gems/hyrax-2.0.1/app/views/hyrax/dashboard/profiles/show.html.erb
```

## Stack trace:
```
hyrax (2.0.1) app/search_builders/hyrax/abstract_type_relation.rb:28:in `delegated_attributes'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:279:in `field_name_for'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:272:in `condition_to_clauses'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:266:in `block in create_query_from_hash'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:266:in `each'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:266:in `map'
active-fedora (11.5.2) lib/active_fedora/relation/finder_methods.rb:266:in `create_query_from_hash'
active-fedora (11.5.2) lib/active_fedora/relation/query_methods.rb:70:in `build_where'
active-fedora (11.5.2) lib/active_fedora/relation/query_methods.rb:60:in `where!'
active-fedora (11.5.2) lib/active_fedora/relation/query_methods.rb:56:in `where'
hyrax (2.0.1) app/helpers/hyrax/dashboard_helper_behavior.rb:12:in `number_of_works'
hyrax (2.0.1) app/views/hyrax/users/_vitals.html.erb:11:in `__usr_local_bundle_gems_hyrax_______app_views_hyrax_users__vitals_html_erb___2025025881464074725_47621080'
actionview (5.0.6) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.6) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.6) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.6) lib/action_view/template.rb:157:in `render'
actionview (5.0.6) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
actionview (5.0.6) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
actionview (5.0.6) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.6) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.6) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.0.6) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.0.6) lib/action_view/helpers/rendering_helper.rb:35:in `render'
hyrax (2.0.1) app/views/hyrax/dashboard/profiles/show.html.erb:15:in `__usr_local_bundle_gems_hyrax_______app_views_hyrax_dashboard_profiles_show_html_erb___16601125103397573_50242920'
actionview (5.0.6) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.6) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.6) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.6) lib/action_view/template.rb:157:in `render'
actionview (5.0.6) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.6) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.6) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.6) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.6) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.6) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.6) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.6) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.6) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.6) lib/action_view/rendering.rb:104:in `_render_template'
actionpack (5.0.6) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.6) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.6) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.6) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.6) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.6) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.6) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.0.6) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.6) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.6) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.6) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.6) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.6) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.6) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
railties (5.0.6) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.6) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
active-fedora (11.5.2) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mjgiarlo** [comment]
@paulwalk That looks like there are no generated concerns. The error occurs because this line returns `nil`:

https://github.com/samvera/hyrax/blob/v2.0.1/app/search_builders/hyrax/abstract_type_relation.rb#L24

Did you restart your Rails server after generating the `DataSet` work type? Can you confirm your Hyrax initializer contains a line like the following: https://github.com/sul-dlss/hydrox/blob/master/config/initializers/hyrax.rb#L5 ?

**Comment by paulwalk** [comment]
thanks @mjgiarlo for this really helpful response - I now know what I was doing wrong. I am deploying Hyrax in a series of Docker containers. I'm using external docker volumes to persist data when the containers are restarted (i.e. for the Rails DB, the SOLR index, the Fedora data) but I had not done this for the Rails application itself. I didn't; quite register that the rake task for creating a new work type would overwrite the application code. Consequently, when the container was restarted, the changes were overwritten with the vanilla application code from the docker image.

Solution:
1. map the Rails application root directory to an external docker volume
2. re-run `rails generate hyrax:work DataSet`
3. `docker-compose down`
4. `docker-compose up`

Now it works  :-)

Thanks again!

**Comment by mjgiarlo** [comment]
@paulwalk Excellent! Glad it was a quick fix.
