### ISSUE TITLE
Hyrax depends on behavior that was removed in ActiveFedora 12

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2482]
The `equivalent_class?` method was removed https://github.com/samvera/active_fedora/commit/c356557fa81e21464754c454defa675187b1e08b#diff-7b13f67c86af38484d2f3164632ce4eaL209  but we're trying to override it here: https://github.com/samvera/hyrax/blob/45281bc7e6eba3fc27800f7625956657f47ddd8f/app/search_builders/hyrax/abstract_type_relation.rb#L11

So this causes:

```
      ActiveFedora::ModelMismatch:
        Expected Hyrax::AbstractTypeRelation::DummyModel. Got: GenericWork
      # ./vendor/bundle/ruby/2.4.0/gems/active-fedora-12.0.0/lib/active_fedora/relation/finder_methods.rb:198:in `class_to_load'
      # ./vendor/bundle/ruby/2.4.0/gems/active-fedora-12.0.0/lib/active_fedora/relation/finder_methods.rb:185:in `load_from_fedora'
      # ./vendor/bundle/ruby/2.4.0/gems/active-fedora-12.0.0/lib/active_fedora/relation/finder_methods.rb:171:in `find_one'
      # ./vendor/bundle/ruby/2.4.0/gems/active-fedora-12.0.0/lib/active_fedora/relation/finder_methods.rb:214:in `find_with_ids'
      # ./vendor/bundle/ruby/2.4.0/gems/active-fedora-12.0.0/lib/active_fedora/relation/finder_methods.rb:48:in `find'
```

**Comment by no-reply** [comment]
See also: #2130

**Comment by no-reply** [comment]
This will be fixed by https://github.com/samvera/active_fedora/issues/1306.

**Comment by no-reply** [comment]
12.0.2 released.
