### ISSUE TITLE
I18n::InvalidLocale should be rescued

### ISSUE THREAD

**Issue by sandbergja** [samvera/hyrax#2637]
### Descriptive summary

When a user enters an invalid locale (e.g. http://libarchive.linnbenton.edu/concern/newspaper_issues/8s45q876k?locale=jv), they get a 500 error.  In the interest of giving the user *something* they can view, I would propose catching this error and sending the user to the appropriate page using the value of `I18n.default_locale`.

### Rationale

While it's not too likely that a user requests a locale that doesn't exist, it is technically possible (and happens occasionally, according to my logs).  If a user does this, they get the app's 500 error page.  Displaying a page with a language picker (rather than the 500 page) would allow the user to recover by choosing another, available locale.

**Comment by jcoyne** [comment]
We handle this in Hyku by rendering the 404 page: https://github.com/samvera-labs/hyku/blob/02c16209c2afc74be1f83a64f322a88711c28345/config/application.rb#L22

**Comment by mjgiarlo** [comment]
I dig the idea. We could consider adding a message to the flash as well.

Would you mind attaching a backtrace to this issue as well? Thanks, @sandbergja! (And, of course, pull requests are most welcome.)

**Comment by sandbergja** [comment]
I like the idea of a flash message!  Here's the backtrace:

    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] i18n (0.8.6) lib/i18n.rb:284:in `enforce_available_locales!'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] i18n (0.8.6) lib/i18n/config.rb:13:in `locale='
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionview (5.1.2) lib/action_view/lookup_context.rb:268:in `locale='
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionview (5.1.2) lib/action_view/rendering.rb:19:in `locale='
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] i18n (0.8.6) lib/i18n.rb:35:in `locale='
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] hyrax (2.0.0) app/controllers/concerns/hyrax/controller.rb:34:in `set_locale'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:413:in `block in make_lambda'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:198:in `block in halting'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:507:in `block in invoke_before'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:507:in `each'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:507:in `invoke_before'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:130:in `run_callbacks'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] warden (1.2.7) lib/warden/manager.rb:35:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/etag.rb:25:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/head.rb:12:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] active-fedora (11.5.2) lib/active_fedora/ldp_cache.rb:26:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] lograge (0.3.6) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] /var/www/hyrax/shared/bundle/ruby/2.4.0/bundler/gems/syslogger-eb7df0b811fd/lib/syslogger.rb:121:in `block in tagged'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] /var/www/hyrax/shared/bundle/ruby/2.4.0/bundler/gems/syslogger-eb7df0b811fd/lib/syslogger.rb:185:in `tagged'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] /var/www/hyrax/shared/bundle/ruby/2.4.0/bundler/gems/syslogger-eb7df0b811fd/lib/syslogger.rb:121:in `tagged'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] sentry-raven (2.6.3) lib/raven/integrations/rack.rb:50:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] railties (5.1.2) lib/rails/engine.rb:522:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] puma (3.9.1) lib/puma/configuration.rb:224:in `call'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] puma (3.9.1) lib/puma/server.rb:435:in `process_client'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] puma (3.9.1) lib/puma/server.rb:299:in `block in run'
    [12c6cdb6-dd88-4e91-abd3-6ce95f500904] puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
