### ISSUE TITLE
New collection issue on development not letting me create collection

### ISSUE THREAD

**Issue by snawar92** [samvera/hyrax#2675]
### Descriptive summary

i am working all on latest code you provided installed app using

rails _5.0.6_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v2.0.1/template.rb

i am facing issue on creating new collection 
this comes up in view

```
NoMethodError in Hyrax::Dashboard::Collections#new

Showing /Users/cybercoders-18556/.rvm/gems/ruby-2.4.2/gems/hyrax-2.0.1/app/views/hyrax/dashboard/collections/_form.html.erb where line #24 raised:

undefined method `primary_terms' for #<Collection:0x00007fe48d1ec408>

```

this is in terminal below one 
```
Attempted to init base path `dev`, but it already exists
  Load LDP (27.8ms) http://127.0.0.1:8984/rest/dev/33/90/06/85/33900685-8999-4951-a2de-32461f0e25e0 Service: 70309827558420
  Rendering /Users/cybercoders-18556/.rvm/gems/ruby-2.4.2/gems/hyrax-2.0.1/app/views/hyrax/dashboard/collections/new.html.erb within layouts/dashboard
  Rendered /Users/cybercoders-18556/.rvm/gems/ruby-2.4.2/gems/hyrax-2.0.1/app/views/hyrax/dashboard/collections/_form.html.erb (33.0ms)
  Rendered /Users/cybercoders-18556/.rvm/gems/ruby-2.4.2/gems/hyrax-2.0.1/app/views/hyrax/dashboard/collections/new.html.erb within layouts/dashboard (47.7ms)
Completed 401 Unauthorized in 373ms (ActiveRecord: 1.5ms)


  
ActionView::Template::Error (undefined method `primary_terms' for #<Collection:0x00007fe48d1ec408>):
    21: 
    22:             <h2 class="non lower"><%= t('hyrax.collection.form.description') %></h2>
    23:             <div id="base-terms">
    24:               <% f.object.primary_terms.each do |term| %>
    25:                 <%= render_edit_field_partial(term, f: f) %>
    26:               <% end %>
    27: 
  
activemodel (5.1.5) lib/active_model/attribute_methods.rb:432:in `method_missing'
hyrax (2.0.1) app/views/hyrax/dashboard/collections/_form.html.erb:24:in `block in ___sers_cybercoders________rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_dashboard_collections__form_html_erb___704095761573295183_70309819759880'
actionview (5.1.5) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.1.5) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
actionview (5.1.5) lib/action_view/helpers/capture_helper.rb:39:in `capture'
actionview (5.1.5) lib/action_view/helpers/form_helper.rb:450:in `form_for'
simple_form (3.5.1) lib/simple_form/action_view_extensions/form_helper.rb:27:in `block in simple_form_for'
simple_form (3.5.1) lib/simple_form/action_view_extensions/form_helper.rb:46:in `with_simple_form_field_error_proc'

```

**Comment by snawar92** [comment]
i figured out ht e issue that was simple_form version issue set version to (3.5.0)
