### ISSUE TITLE
Uglifier::Error: Invalid assignment

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#2931]
### Descriptive summary

In Hyrax 2.1.0.beta2 a generated application cannot be deployed to a production environment because the js compression fails with the error:

```
** Execute deploy:updated
** Invoke deploy:compile_assets (first_time)
** Invoke deploy:set_rails_env
** Execute deploy:compile_assets
** Invoke deploy:assets:precompile (first_time)
** Execute deploy:assets:precompile
00:09 deploy:assets:precompile
      01 bundle exec rake assets:precompile
      01 Yarn executable was not detected in the system.
      01 Download Yarn at https://yarnpkg.com/en/docs/install
      01 rake aborted!
      01 Uglifier::Error: Invalid assignment
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/uglifier-4.1.8/lib/uglifier.rb:234:in `parse_result'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/uglifier-4.1.8/lib/uglifier.rb:216:in `run_uglifyjs'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/uglifier-4.1.8/lib/uglifier.rb:168:in `compile'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
      01 /opt/nurax/shared/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
      01 /usr/local/bin/bundle:30:in `block in <main>'
      01 /usr/local/bin/bundle:22:in `<main>'
      01 Tasks: TOP => assets:precompile
```

### Rationale

It appears that applications running the latest version of Hyrax won't deploy to a production environment. This should be fixed.

### Steps to reproduce the behavior

Try to deploy nurax: https://github.com/curationexperts/nurax
This is the app we use for release testing and it currently cannot deploy.

### Related work

Seems like this might have been introduced in this PR? 

https://github.com/samvera/hyrax/pull/2870/files

**Comment by jcoyne** [comment]
Seems like https://github.com/lautis/uglifier/issues/132

**Comment by no-reply** [comment]
What's the current status of this issue? It looks like the upstream is still open.

@bess are you still having trouble doing asset precompile on recent Hyraxes?

**Comment by no-reply** [comment]
we run asset precompile regularly in the docker builds. there was related work attached to #4705.

closing this as (hopefully) fixed by that work. please reopen if this is resurfacing.
