### ISSUE TITLE
Hyrax::FileSetFixityCheckService throws error on fileset with non-versioned file

### ISSUE THREAD

**Issue by coblej** [samvera/hyrax#3000]
### Descriptive summary

Hyrax versions: 2.0.0; current master HEAD
When Hyrax::FileSetFixityCheckService runs on a fileset that contains a non-versioned file, it throws an error:
```
     Failure/Error: versions = [versions.max_by(&:created)] if latest_version_only
     
     NoMethodError:
       undefined method `created' for #<Hydra::PCDM::File:0x007fac1bfef6e0>
       Did you mean?  create_date
                      create_or_update
                      creator
     # /Users/coblej/.rvm/gems/ruby-2.3.1@hyrax/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
     # ./app/services/hyrax/file_set_fixity_check_service.rb:81:in `each'
     # ./app/services/hyrax/file_set_fixity_check_service.rb:81:in `max_by'
     # ./app/services/hyrax/file_set_fixity_check_service.rb:81:in `fixity_check_file'
```

The `#fixity_check_file` method appears to accommodate non-versioned files by setting the `versions` variable to an array containing the file (which is a `Hydra::PCDM::File`) rather than one containing a `ActiveFedora::VersionsGraph::ResourceVersion` -- cf.  https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L79.  This causes a problem in the next line -- https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L81 -- where `#max_by(&:created)` is called on the `versions` object.  This works fine when the `versions` array contains a `ActiveFedora::VersionsGraph::ResourceVersion` but not when it contains a `Hydra::PCDM::File`, which does not have a `#created` method.

### Rationale

We encountered this bug in `v2.0.0` when we uploaded a file which triggered the creation of an `extractedText` file in the fileset along with the `originalFile`.  The `originalFile` is versioned but the `extractedText` file is not.  Since `Hyrax::FileSetFixityCheckService` checks all the files in the fileset, it threw the error noted above when it tried to check the `extractedText` file.

### Expected behavior

Running `Hyrax::FileSetFixityCheckService` on a non-versioned file (that is, one that returns `false` for `#has_versions?`) should not throw an error.

### Actual behavior

Running `Hyrax::FileSetFixityCheckService` on a non-versioned file (that is, one that returns `false` for `#has_versions?`) throws an error.

### Steps to reproduce the behavior

1. Create a fileset that contains a non-versioned file; e.g., an `extractedText` file.
2. Instantiate `Hyrax::FileSetFixityCheckService` with that fileset and with the `latest_version_only` argument set to `true`.
3. Call `#fixity_check` on the `Hyrax::FileSetFixityCheckService` instance.

### Related work

Link to related tickets or prior related work here.

**Comment by coblej** [comment]
My proposed fix for this is to change https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L81 from 
```
versions = [versions.max_by(&:created)] if latest_version_only
```
to
```
versions = [versions.max_by(&:created)] if file.has_versions? && latest_version_only
```
so that the code on that line is executed only for files that have versions, in which case the `versions` array contains an object (`ActiveFedora::VersionsGraph::ResourceVersion`) that responds to `#created` rather than one that does not (namely, a `Hydra::PCDM::File`).
