### ISSUE TITLE
ImportUrlJob not retrieving operation

### ISSUE THREAD

**Issue by kdid** [samvera/hyrax#3046]
### Descriptive summary

We are using the ImportUrlJob for our batch import job. With the most recent Hyrax updates (2.1.0 rc1), we are getting an error when we try to import works.

https://github.com/samvera/hyrax/blob/master/app/jobs/import_url_job.rb#L18

```
undefined method `merge' for #<FileSet:0x007fe156b57090>
/Users/ksd927/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/ksd927/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-93d66ca7e703/app/jobs/import_url_job.rb:18:in `reduce'
/Users/ksd927/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-93d66ca7e703/app/jobs/import_url_job.rb:18:in `operation'
/Users/ksd927/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-93d66ca7e703/app/jobs/import_url_job.rb:13:in `block in <class:ImportUrlJob>'
```

### Rationale

Ingesting a work is core functionality.

**Comment by cjcolvar** [comment]
Just looking at the changes in the job class I'm unsure how this error could arise.  Can you provide the code that invokes this job where the error happens?  Thanks!

**Comment by kdid** [comment]
@cjcolvar I'm thinking it arose by making the changes to add keyword arguments and then remove them but not revert the other changes?

https://github.com/samvera/hyrax/pull/2128/commits/0a66080d8e914d19a1ea0f52c5f6d3ef0dbb22ab

Yes, I can try to write a failing test.

**Comment by cjcolvar** [comment]
@kdid Thanks!
I was thinking along the same lines but the tests are still passing and nothing immediately looks wrong to me.  I'm guessing the failing test will be insightful.
