### ISSUE TITLE
Find cause of random collection_type_spec failure

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3052]
### Descriptive summary

Travis is randomly returning the following spec failure. This does not happen locally.

```1) Hyrax::CollectionType collections returns collections of this collection type
     Failure/Error: expect(collection_type.collections.to_a).to include collection
     
     ActiveFedora::ObjectNotFoundError:
       Couldn't find ActiveFedora::Base with 'id'=object_id_46


rspec ./spec/models/hyrax/collection_type_spec.rb:140 # Hyrax::CollectionType collections returns collections of this collection type```

**Comment by laritakr** [comment]
Here's the backtrace info from my most recent build:
```  1) Hyrax::CollectionType collections returns collections of this collection type
     Failure/Error: expect(collection_type.collections.to_a).to include collection
     
     ActiveFedora::ObjectNotFoundError:
       Couldn't find ActiveFedora::Base with 'id'=col-3-dep
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:201:in `raise_record_not_found_exception!'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:195:in `load_from_fedora'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:131:in `block (2 levels) in find_each'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:129:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:129:in `block in find_each'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:167:in `block in search_in_batches'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:163:in `loop'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:163:in `search_in_batches'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:128:in `find_each'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation.rb:59:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation.rb:59:in `to_a'
     # ./vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation.rb:59:in `to_a'
     # ./spec/models/hyrax/collection_type_spec.rb:141:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:609:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'```
