### ISSUE TITLE
App throws rails error instead of work visibility notification 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3403]
### Descriptive summary
Hyrax 3.0.0rc testing   
```
QA Testing for Hyrax
Hyrax Version: 2.4.0
Hyrax Branch: master
Hyrax Revision: c41b819a6e396a5cd78c91c7b691d1bed39662ad
© 2018 Samvera-Hyrax
Nurax Version
ENV: production
SHA: 1d80945a9d26b798207eec54feef1e035336a414
Branch: 2018-11-13-10-00
Updated: 13 Nov 2018 16:00:30
```
Test: [SD_1.11](https://docs.google.com/spreadsheets/d/1Hxq3VIdKy35Hr_-OQkyiEYXZNOap8_LUbWCM6hl8oZU/edit#gid=248186373)
```
User not signed in: Make sure you can't see this: https://nurax-dev.curationexperts.com/collections/8k71nh116?locale=en
```
### Rationale
App throws rails error instead of work visibility notification 
### Expected behavior
A not signed in user who wants to access a non public work should see a message telling visibility restrictions apply.  

### Actual behavior
getting a rails error when visiting  https://nurax-dev.curationexperts.com/collections/8k71nh116?locale=en  as non logged-in user 
```
Ldp::Gone in Hyrax::CollectionsController#show 
Extracted source (around line #119): 
    resp.tap do |resp|
      unless resp.status < 400
        raise case resp.status
          when 400
            if resp.env.method == :head
              # If the request was a HEAD request (which only retrieves HTTP headers),

Rails.root: /opt/nurax/releases/20181113160030
Application Trace | Framework Trace | Full Trace

ldp (0.7.2) lib/ldp/client/methods.rb:119:in `block in check_for_errors'
ldp (0.7.2) lib/ldp/client/methods.rb:117:in `tap'
ldp (0.7.2) lib/ldp/client/methods.rb:117:in `check_for_errors'
ldp (0.7.2) lib/ldp/client/methods.rb:25:in `block in head'
activesupport (5.1.6) lib/active_support/notifications.rb:168:in `instrument'
ldp (0.7.2) lib/ldp/client/methods.rb:17:in `head'
/usr/local/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
active-fedora (11.5.4) lib/active_fedora/initializing_connection.rb:22:in `head'
ldp (0.7.2) lib/ldp/resource.rb:59:in `head'
ldp (0.7.2) lib/ldp/resource.rb:42:in `new?'
active-fedora (11.5.4) lib/active_fedora/relation/finder_methods.rb:195:in `load_from_fedora'
active-fedora (11.5.4) lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
active-fedora (11.5.4) lib/active_fedora/relation/finder_methods.rb:234:in `find_with_ids'
active-fedora (11.5.4) lib/active_fedora/relation/finder_methods.rb:52:in `find'
active-fedora (11.5.4) lib/active_fedora/querying.rb:3:in `find'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-c41b819a6e39/app/controllers/concerns/hyrax/collections_controller_behavior.rb:28:in `show'
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
active-fedora (11.5.4) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.4.0) lib/flipflop/feature_cache.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (3.3.0) lib/honeybadger/agent.rb:337:in `with_rack_env'
honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Request

Parameters:

{"locale"=>"en", "id"=>"8k71nh116"}

Toggle session dump:
_csrf_token: "/Io+Zzih+NHfJE2HYR+Wr2DAP+Z8TNKZju9wmoWNUxA="
history: [5788655, 5788649, 5788648, 5788642, 5788641, 5788640, 5788639, 5788633]
search: {"id"=>5788655, "counter"=>nil, "per_page"=>nil}
session_id: "fa1450fb6e1cd56fc5e09a391613725a"

Toggle env dump:
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "134.147.13.220"
SERVER_NAME: "nurax-dev.curationexperts.com"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None
```
### Steps to reproduce the behavior
0. logout of https://nurax-dev.curationexperts.com
1. Visit https://nurax-dev.curationexperts.com/collections/8k71nh116?locale=en

### Related work

Link to related tickets or prior related work here.

**Comment by chrisdaaz** [comment]
i can't read rails errors, but i think that particular might have been deleted. there should probably be a way to return a 404 message when a collection or work or item has been deleted.
