### ISSUE TITLE
Docker Compose hyrax_sidekiq error

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#4897]
In looking at the `docker compose up` logs, it appears that there are problems regarding the sidekiq container.

```sh
bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile
/usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
...
```

**Comment by no-reply** [comment]
is this ticket different from #4896?

**Comment by no-reply** [comment]
is this still active?
