### ISSUE TITLE
Unrescueable UnknownFormat errors for work/fileset pages

### ISSUE THREAD

**Issue by bbpennel** [samvera/hyrax#5049]
### Descriptive summary

There is an uncaught fatal error when bots attempt to download XML representations of our works. We are experiencing it in our local hyrax 2.9.5 repository, and it is easy demonstrated in nurax by adding .xml to the end of the URL:
https://nurax-dev.curationexperts.com/concern/generic_works/w9505077h.xml?locale=en
Adding a `rescue_from ActionController::UnknownFormat` does not appear to work for handling these errors.

### Rationale

The rate of hits we get on these URLs varies from month to month, but we've had ~10000 of these fatal errors/stack traces show up in our logs in July, which is making the logs rather hard to work with. I haven't been able to figure out why various search engines have been trying these URLs, since I don't see any links to them or in our site map.

### Expected behavior

This error should result in a 4xx response and/or be rescuable.

### Actual behavior

We have tried updating our application_controller.rb to rescue UnknownFormat errors:
```
  rescue_from ActionController::UnknownFormat, with: -> { render_415 }

  protected
    def render_415
      render 'errors/not_found', status: 415
    end
```
But it does not appear to have any affect. We are able to catch other simple routing errors this way, such as `ActionController::RoutingError`, but not these particular UnknownFormat errors.

We get a very similar error when a request is made to a FileSet url, where .xml is appended to the end of the identify:
```
2021-04-15 01:08:08 -0400 - FATAL: [d5e780f0-ade9-481a-8790-b8d6bb0ceb28] ActionController::UnknownFormat (ActionController::UnknownFor
mat):
2021-04-15 01:08:08 -0400 - FATAL: [d5e780f0-ade9-481a-8790-b8d6bb0ceb28]   
2021-04-15 01:08:08 -0400 - FATAL: [d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/mime_responds.
rb:203:in `respond_to'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] hyrax (2.6.0) app/controllers/hyrax/file_sets_controller.rb:40:in `show'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/abstract_controller/base.rb:186:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/rendering.rb:30:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] activesupport (5.1.7) lib/active_support/callbacks.rb:131:in `run_callbacks'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/rescue.rb:20:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] activesupport (5.1.7) lib/active_support/notifications.rb:166:in `block in instrument'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] activesupport (5.1.7) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] activesupport (5.1.7) lib/active_support/notifications.rb:166:in `instrument'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] activerecord (5.1.7) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/abstract_controller/base.rb:124:in `process'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionview (5.1.7) lib/action_view/rendering.rb:30:in `process'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal.rb:189:in `dispatch'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_controller/metal.rb:253:in `dispatch'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `each'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `serve'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:844:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] rack (2.2.3) lib/rack/head.rb:12:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[d5e780f0-ade9-481a-8790-b8d6bb0ceb28] active-fedora (11.5.4) lib/active_fedora/ldp_cache.rb:26:in `call'
```

I'm not sure how this sort of error should be handled other than overriding the controllers to add rescues, since the applicaton_controller does not seem to be able to handle it.

### Steps to reproduce the behavior
Add .xml to the end of the identifier on a work or fileset page. See above.

**Comment by no-reply** [comment]
thanks for this report (and sorry for the slow response, i've been on vacation).

it looks like we should get some handling for the `415` into Hyrax's default controller setup.

it should be possible for apps to address this themselves, though i can't see why your proposed solution isn't working for you. there shouldn't (hopefully isn't) anything special going on here beyond the normal Rails controller error handling, so i'd encourage you to continue to explore application side solutions. that said, i do think Hyrax should provide handling by default. the Hyrax Maintenance Working Group can pick that work up and we'll update with any relevant info we find in the process.
