### ISSUE TITLE
Javascript cannot be tested in docker-compose

### ISSUE THREAD

**Issue by marrus-sh** [samvera/hyrax#5298]
### Descriptive summary

The Jasmine (Javascript) tests currently do not run, resulting in an rspec test failure when testing in a `docker-compose` environment.

### Rationale

It should be possible to test the Hyrax javascripts in `docker-compose`.

### Expected behavior

Jasmine tests should run.

### Actual behavior

Jasmine tests fail with an error of `sh: phantomjs: not found`.

### Steps to reproduce the behavior

    docker-compose exec app sh
    cd ../hyrax-engine
    bundle exec rspec ./spec/javascripts/

**Comment by marrus-sh** [comment]
Both the `jasmine` gems we use and `phantomjs` are no longer maintained and we should strongly consider migrating away from them. [Teaspoon](https://github.com/jejacks0n/teaspoon) appears to be the contemporary replacement (short of doing things through NPM), and I attempted to get it set up [on the `teaspoon` branch](https://github.com/samvera/hyrax/compare/teaspoon), but got errors when running which seemed related to the `device-guests` gem :—

```
bundler: failed to load command: teaspoon (/usr/local/bundle/bin/teaspoon)
Traceback (most recent call last):
	82: from /usr/local/bundle/bin/bundle:23:in `<main>'
	81: from /usr/local/bundle/bin/bundle:23:in `load'
	80: from /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
	79: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	78: from /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
	77: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
	76: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	75: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
	74: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	73: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	72: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	71: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
	70: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
	69: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
	68: from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
	67: from /usr/local/bundle/bin/teaspoon:23:in `<top (required)>'
	66: from /usr/local/bundle/bin/teaspoon:23:in `load'
	65: from /usr/local/bundle/gems/teaspoon-1.2.2/bin/teaspoon:6:in `<top (required)>'
	64: from /usr/local/bundle/gems/teaspoon-1.2.2/bin/teaspoon:6:in `new'
	63: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/command_line.rb:15:in `initialize'
	62: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/command_line.rb:15:in `new'
	61: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/console.rb:10:in `initialize'
	60: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/environment.rb:6:in `load'
	59: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/environment.rb:62:in `load_rails'
	58: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/environment.rb:20:in `require_environment'
	57: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/environment.rb:47:in `require_env'
	56: from /usr/local/bundle/gems/teaspoon-1.2.2/lib/teaspoon/environment.rb:47:in `load'
	55: from /app/samvera/hyrax-engine/spec/teaspoon_env.rb:4:in `<top (required)>'
	54: from /app/samvera/hyrax-engine/spec/teaspoon_env.rb:4:in `require'
	53: from /app/samvera/hyrax-engine/.dassie/config/environment.rb:5:in `<top (required)>'
	52: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
	51: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
	50: from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	49: from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	48: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	47: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
	46: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
	45: from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	44: from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	43: from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	42: from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	41: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	40: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
	39: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
	38: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
	37: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:10:in `execute'
	36: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/file_update_checker.rb:83:in `execute'
	35: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	34: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:20:in `reload!'
	33: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	32: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:41:in `each'
	31: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	30: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `load'
	29: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	28: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `block in load'
	27: from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	26: from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	25: from /app/samvera/hyrax-engine/.dassie/config/routes.rb:3:in `<main>'
	24: from /usr/local/bundle/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:414:in `draw'
	23: from /usr/local/bundle/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	22: from /usr/local/bundle/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	21: from /app/samvera/hyrax-engine/.dassie/config/routes.rb:15:in `block in <main>'
	20: from /usr/local/bundle/gems/devise-4.8.1/lib/devise/rails/routes.rb:242:in `devise_for'
	19: from /usr/local/bundle/gems/devise-4.8.1/lib/devise/rails/routes.rb:242:in `each'
	18: from /usr/local/bundle/gems/devise-4.8.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
	17: from /usr/local/bundle/gems/devise-4.8.1/lib/devise.rb:357:in `add_mapping'
	16: from /usr/local/lib/ruby/2.7.0/set.rb:328:in `each'
	15: from /usr/local/lib/ruby/2.7.0/set.rb:328:in `each_key'
	14: from /usr/local/bundle/gems/devise-4.8.1/lib/devise.rb:357:in `block in add_mapping'
	13: from /usr/local/bundle/gems/devise-guests-0.8.1/lib/devise-guests/controllers/helpers.rb:82:in `define_helpers'
	12: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	11: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:42:in `each'
	10: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	 9: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 8: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 7: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	 6: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	 5: from /usr/local/bundle/gems/devise-guests-0.8.1/lib/devise-guests/controllers/helpers.rb:87:in `block in define_helpers'
	 4: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:675:in `set_callback'
	 3: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:625:in `__update_callbacks'
	 2: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:625:in `reverse_each'
	 1: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:627:in `block in __update_callbacks'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:676:in `block in set_callback': undefined method `append' for nil:NilClass (NoMethodError)
```

**Comment by cjcolvar** [comment]
FWIW We went the NPM route for jasmine tests in `hydra-editor`: https://github.com/samvera/hydra-editor/pull/203/commits/ad81f2d25e5899d35a96f5a48ebaf191b62d74ea
