### ISSUE TITLE
Bug: Cannot update Collection metadata after banner is attached.

### ISSUE THREAD

**Issue by bwatson78** [samvera/hyrax#5501]
### Descriptive summary

Within a recently upgraded application (now Hyrax v3.3.0), as well as Dassie/Docker app of the same version, we are receiving errors when attempting to update any collection's metadata field while a banner has been saved.

```
app_1         | I, [2022-03-07T20:34:02.375120 #1]  INFO -- : Started PATCH "/dashboard/collections/gx41mh844?locale=en" for 192.168.0.1 at 2022-03-07 20:34:02 +0000
app_1         | I, [2022-03-07T20:34:02.381051 #1]  INFO -- : Processing by Hyrax::Dashboard::CollectionsController#update as HTML
app_1         | I, [2022-03-07T20:34:02.381272 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"HfeZOQvksEEci2zWYjjRwxcFAxVkwBywdqllnJMmzhc26z+14MrkLGL+4MdixuE1JqYIt3Pk21VNr7q6ni0dvQ==", "collection"=>{"title"=>["Bob's Collection-", ""], "description"=>[""], "thumbnail_id"=>"", "alternative_title"=>[""], "creator"=>[""], "contributor"=>[""], "keyword"=>[""], "license"=>[""], "publisher"=>[""], "date_created"=>[""], "subject"=>[""], "language"=>[""], "identifier"=>[""], "based_near"=>[""], "related_url"=>[""], "resource_type"=>[""]}, "type"=>"", "stay_on_edit"=>"true", "collection_type_gid"=>"gid://dassie/Hyrax::CollectionType/1", "files"=>["", ""], "banner_unchanged"=>"true", "permission_template"=>{"access_grants_attributes"=>{"0"=>{"agent_type"=>"group", "agent_id"=>"", "access"=>""}}}, "update_collection"=>"Save changes", "referer_anchor"=>"#description", "locale"=>"en", "id"=>"gx41mh844"}
app_1         | D, [2022-03-07T20:34:02.384199 #1] DEBUG -- :   Hyrax::Feature Load (0.5ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "read_only"], ["LIMIT", 1]]
app_1         | D, [2022-03-07T20:34:02.384445 #1] DEBUG -- :   ↳ /app/samvera/hyrax-engine/app/controllers/concerns/hyrax/controller.rb:140
app_1         | D, [2022-03-07T20:34:02.386752 #1] DEBUG -- :   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
app_1         | D, [2022-03-07T20:34:02.387034 #1] DEBUG -- :   ↳ /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/log_subscriber.rb:98
fcrepo_1      | INFO 20:34:02.392 (FedoraLdp) HEAD for: dev/gx/41/mh/84/gx41mh844
fcrepo_1      | INFO 20:34:02.397 (FedoraLdp) GET resource 'dev/gx/41/mh/84/gx41mh844'
app_1         | D, [2022-03-07T20:34:02.408308 #1] DEBUG -- :   Load LDP (14.2ms) http://fcrepo:8080/rest/dev/gx/41/mh/84/gx41mh844 Service: 622340
app_1         | D, [2022-03-07T20:34:02.445310 #1] DEBUG -- : Usergroups are ["public", "admin", "registered"]
app_1         | D, [2022-03-07T20:34:02.447478 #1] DEBUG -- :   Hyrax::Feature Load (0.4ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "transfer_works"], ["LIMIT", 1]]
app_1         | D, [2022-03-07T20:34:02.447645 #1] DEBUG -- :   ↳ /app/samvera/hyrax-engine/app/models/concerns/hyrax/ability.rb:189
app_1         | D, [2022-03-07T20:34:02.448621 #1] DEBUG -- :   Hyrax::Feature Load (0.3ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "proxy_deposit"], ["LIMIT", 1]]
app_1         | D, [2022-03-07T20:34:02.448786 #1] DEBUG -- :   ↳ /app/samvera/hyrax-engine/app/models/concerns/hyrax/ability.rb:195
app_1         | D, [2022-03-07T20:34:02.451898 #1] DEBUG -- :   CollectionBrandingInfo Load (0.5ms)  SELECT  "collection_branding_infos".* FROM "collection_branding_infos" WHERE "collection_branding_infos"."collection_id" = $1 AND "collection_branding_infos"."role" = $2 ORDER BY "collection_branding_infos"."id" ASC LIMIT $3  [["collection_id", "gx41mh844"], ["role", "banner"], ["LIMIT", 1]]
app_1         | D, [2022-03-07T20:34:02.452061 #1] DEBUG -- :   ↳ /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:290
app_1         | I, [2022-03-07T20:34:02.453740 #1]  INFO -- : Completed 500 Internal Server Error in 72ms (ActiveRecord: 2.4ms)
app_1         |
app_1         |
app_1         | F, [2022-03-07T20:34:02.454873 #1] FATAL -- :
app_1         | F, [2022-03-07T20:34:02.454953 #1] FATAL -- : ArgumentError (same file: /app/samvera/hyrax-webapp/public/branding/gx41mh844/banner/1W7vXZ6.gif and /app/samvera/hyrax-webapp/public/branding/gx41mh844/banner/1W7vXZ6.gif):
app_1         | F, [2022-03-07T20:34:02.455015 #1] FATAL -- :
app_1         | F, [2022-03-07T20:34:02.455087 #1] FATAL -- : /app/samvera/hyrax-engine/app/models/collection_branding_info.rb:21:in `save'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:290:in `update_existing_banner'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:282:in `process_banner_input'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:150:in `update'
app_1         | /usr/local/lib/ruby/2.7.0/fileutils.rb:1588: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/lib/ruby/2.7.0/fileutils.rb:1605: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/lib/ruby/2.7.0/fileutils.rb:1587: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/lib/ruby/2.7.0/fileutils.rb:539: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/valkyrie-2.2.0/lib/valkyrie/storage/disk.rb:20: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /app/samvera/hyrax-engine/app/models/collection_branding_info.rb:21: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:290: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:282: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /app/samvera/hyrax-engine/app/controllers/hyrax/dashboard/collections_controller.rb:150: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/basic_implicit_render.rb:6: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/abstract_controller/base.rb:194: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/rendering.rb:30: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/abstract_controller/callbacks.rb:42: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/callbacks.rb:132: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/abstract_controller/callbacks.rb:41: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/rescue.rb:22: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/instrumentation.rb:34: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/notifications.rb:168: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/notifications/instrumenter.rb:23: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/notifications.rb:168: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/instrumentation.rb:32: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal/params_wrapper.rb:256: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/railties/controller_runtime.rb:24: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/abstract_controller/base.rb:134: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionview-5.2.6.2/lib/action_view/rendering.rb:32: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal.rb:191: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_controller/metal.rb:252: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/route_set.rb:52: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/route_set.rb:34: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/journey/router.rb:52: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/journey/router.rb:35: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/route_set.rb:840: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/engine.rb:524: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/railtie.rb:190: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/mapper.rb:19: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/mapper.rb:48: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/journey/router.rb:52: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/journey/router.rb:35: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/routing/route_set.rb:840: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:40: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/http/content_security_policy.rb:18: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/cookies.rb:670: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/active-fedora-13.2.5/lib/active_fedora/ldp_cache.rb:26: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/flipflop-2.6.0/lib/flipflop/feature_cache.rb:12: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/migration.rb:559: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/callbacks.rb:28: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/callbacks.rb:98: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/callbacks.rb:26: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/executor.rb:14: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/debug_exceptions.rb:61: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:135: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:30: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:20: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/show_exceptions.rb:33: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/rack/logger.rb:38: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/rack/logger.rb:26: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/tagged_logging.rb:71: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/tagged_logging.rb:28: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/tagged_logging.rb:71: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/rack/logger.rb:26: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/remote_ip.rb:81: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/request_id.rb:27: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/executor.rb:14: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/actionpack-5.2.6.2/lib/action_dispatch/middleware/static.rb:127: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/railties-5.2.6.2/lib/rails/engine.rb:524: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/commonlogger.rb:40: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/configuration.rb:228: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/server.rb:718: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/server.rb:472: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/server.rb:328: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | /usr/local/bundle/gems/puma-4.3.11/lib/puma/thread_pool.rb:134: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
app_1         | /usr/local/bundle/gems/web-console-3.7.0/lib/web_console/exception_mapper.rb:31: warning: in `eval'
app_1         | 192.168.0.1 - - [07/Mar/2022:20:34:02 +0000] "PATCH /dashboard/collections/gx41mh844?locale=en HTTP/1.1" 500 - 0.2261
app_1         | I, [2022-03-07T20:34:02.610796 #1]  INFO -- : Finished "/notifications/endpoint/" [WebSocket] for 192.168.0.1 at 2022-03-07 20:34:02 +0000
app_1         | I, [2022-03-07T20:34:02.611118 #1]  INFO -- : Hyrax::NotificationsChannel stopped streaming from hyrax:notifications:Z2lkOi8vZGFzc2llL1VzZXIvMQ
```

### Rationale

The end user would have to remove any banners before making changes to the metadata fields, which is not the expected behavior.

### Expected behavior

The end user should be able successfully save a collection with new metadata when a banner has been attached to it.

### Actual behavior

The save doesn't process, instead producing the error above.

### Steps to reproduce the behavior

1. Create or choose an already persisted Collection.
2. If the Collection doesn't have a banner attached, attach one in the Edit Collection-Branding area and `Save changes`.
3. While still in the form, attempt to change the text or values of any metadata field and `Save changes`.

**Comment by bwatson78** [comment]
My apologies, I meant the Dassie/Docker bare bones app, not Nurax. I have updated the ticket.

**Comment by bwatson78** [comment]
I brought my local Dassie app to the current version (`1467a570cd2daf8fb063037c0858690452ad0a58`) and the error is gone. Will possibly raise our app's Hyrax version to the same level or wait until a new version is released. Will close this issue.
