### ISSUE TITLE
Extracted Text derivative generation doesn't work for Valkyrie resources.

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#5544]
### Descriptive summary

When generating derivatives extracted text gets pulled out and placed into a direct container as part of the DerivativeService. Unfortunately this won't work with generic Valkyrie - we'll have to update it to use a StorageAdapter appropriately, or something similar.

### Rationale

So it works for everything.

### Expected behavior

Extracted text is added as an attached FileMetadata node to the FileSet, and the binary content is uploaded to the Wings storage adapter.

### Actual behavior

It just errors.

### Steps to reproduce the behavior

1. Upload a PDF
2. View the error:

```
sidekiq_1     | 2022-03-15T21:45:09.027Z pid=1 tid=90dt WARN: ArgumentError: 37720c723 is not an http(s) uri
sidekiq_1     | 2022-03-15T21:45:09.027Z pid=1 tid=90dt WARN: /app/samvera/hyrax-engine/app/services/hyrax/persist_directly_contained_output_file_service.rb:27:in `retrieve_file_set'
sidekiq_1     | /app/samvera/hyrax-engine/app/services/hyrax/persist_directly_contained_output_file_service.rb:15:in `call'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/processors/full_text.rb:9:in `process'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/runners/runner.rb:30:in `block (2 levels) in create'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/runners/runner.rb:27:in `each'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/runners/runner.rb:27:in `block in create'
sidekiq_1     | /app/samvera/hyrax-engine/app/services/hyrax/local_file_service.rb:8:in `call'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/runners/runner.rb:41:in `source_file'
sidekiq_1     | /usr/local/bundle/gems/hydra-derivatives-3.6.1/lib/hydra/derivatives/runners/runner.rb:26:in `create'
sidekiq_1     | /app/samvera/hyrax-engine/app/services/hyrax/file_set_derivatives_service.rb:125:in `extract_full_text'
sidekiq_1     | /app/samvera/hyrax-engine/app/services/hyrax/file_set_derivatives_service.rb:78:in `create_pdf_derivatives'
sidekiq_1     | /app/samvera/hyrax-engine/app/services/hyrax/file_set_derivatives_service.rb:34:in `create_derivatives'
sidekiq_1     | /app/samvera/hyrax-engine/app/jobs/valkyrie_create_derivatives_job.rb:11:in `perform'
sidekiq_1     | /usr/local/bundle/gems/activejob-5.2.6.2/lib/active_job/execution.rb:39:in `block in perform_now'
sidekiq_1     | /usr/local/bundle/gems/activesupport-5.2.6.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
```

### Related work

#5504

**Comment by alishaevn** [comment]
reopening. the related pr was merged, but this needs to go through qa.
