### ISSUE TITLE
Hyrax generator fails (v3.4.2)

### ISSUE THREAD

**Issue by mark-dce** [samvera/hyrax#5922]
### Descriptive summary

The Hyrax generator is failing in v3.4.2 (and v4.0.0beta2).  Running `rails generate hyrax:install` fails with the error "uninitialized constant Dry::Monads::Result::Transformer (NameError)"

### Rationale

When I follow the version specific instructions to start developing a new Hyrax-based app at https://github.com/samvera/hyrax/blob/v3.4.2/documentation/developing-your-hyrax-based-app.md#creating-a-hyrax-based-app, I almost immediately hit an error.  This would be really frustrating to new adopters.

New adopters may want to install and develop against non-dockerized versions of Hyrax.

### Expected behavior
When I use the template or manually run the Hyrax generator, the process should complete successfully so that I can begin developing my institution's Hyrax-based application.

### Actual behavior
The generator fails with the error "uninitialized constant Dry::Monads::Result::Transformer"

NOTE:  I'm seeing the same failure in both v3.4.2 and v4.0.0.beta2
```
% rails generate hyrax:install -f
[DEPRECATION] PCDM is deprecating 'Class#PreservationMasterFile'. Use Class#PreservationFile instead.
/Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:9:in `<class:Result>': uninitialized constant Dry::Monads::Result::Transformer (NameError)
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:8:in `<module:Monads>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:4:in `<module:Dry>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:3:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-transaction-0.13.3/lib/dry/transaction.rb:3:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax/transactions/container.rb:2:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax/transactions.rb:2:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax/engine.rb:34:in `<class:Engine>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax/engine.rb:3:in `<module:Hyrax>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax/engine.rb:2:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hyrax-3.4.2/lib/hyrax.rb:18:in `<main>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
	from /Users/mark/_no_backup_/Projects/test-app/config/application.rb:7:in `<top (required)>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/mark/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from -e:1:in `<main>'
```

#### MANUAL INSTALL
1. Run `rails _5.2.6_ new test-app `
1. `cd test-app`
1. Add `gem 'hyrax', '3.4.2'` to your Gemfile
1. `bundle install`
1. `rails generate hyrax:install -f`
1. Fails with 
    > /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:9:in `<class:Result>': uninitialized constant Dry::Monads::Result::Transformer (NameError)

#### VIA TEMPLATE
1. Follow the instructions in the "Developing Your Hyrax-based Application" docs:
https://github.com/samvera/hyrax/blob/v3.4.2/documentation/developing-your-hyrax-based-app.md#creating-a-hyrax-based-app  
e.g. `rails _5.2.6_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v3.4.2/template.rb`
1. Fails with 
    > /Users/mark/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/dry-monads-1.5.0/lib/dry/monads/result.rb:9:in `<class:Result>': uninitialized constant Dry::Monads::Result::Transformer (NameError)

**Comment by marrus-sh** [comment]
You’ll need 65a7f247cf7e82fd95d6555dea593879d37c63de—there was a breaking dependency change in Dry::Monads/Transformer. New releases with this fix are coming eventually :) .
