### ISSUE TITLE
In valkyrie/fedora, deleting a work results in an error

### ISSUE THREAD

**Issue by dlpierce** [samvera/hyrax#6333]
### Descriptive summary

In valkyrie/fedora, deleting a work results in an error

### Steps to reproduce the behavior in User Interface (UI)

1. Load sirenia (See #6331) 
2. Create a work
3. Delete the work

### Actual behavior (include screenshots if available)

```
Ldp::Gone in Hyrax::MonographsController#destroy
Discovered tombstone resource at /development/98fea2bc-89d5-444c-b9a4-0d629306687a, departed at: 2023-09-28T16:08:48.476750Z

ldp (1.2.0) lib/ldp/client/methods.rb:119:in `block in check_for_errors'
<internal:kernel>:90:in `tap'
ldp (1.2.0) lib/ldp/client/methods.rb:117:in `check_for_errors'
ldp (1.2.0) lib/ldp/client/methods.rb:53:in `block in get'
activesupport (6.1.7.6) lib/active_support/notifications.rb:205:in `instrument'
ldp (1.2.0) lib/ldp.rb:43:in `instrument'
ldp (1.2.0) lib/ldp/client/methods.rb:33:in `get'
valkyrie (3.1.0) lib/valkyrie/persistence/fedora/query_service.rb:108:in `content_with_inbound'
valkyrie (3.1.0) lib/valkyrie/persistence/fedora/query_service.rb:139:in `find_inverse_reference_ids_by_unordered'
valkyrie (3.1.0) lib/valkyrie/persistence/fedora/query_service.rb:123:in `find_inverse_references_by'
/app/samvera/hyrax-engine/app/services/hyrax/custom_queries/find_access_control.rb:20:in `find_access_control_for'
valkyrie (3.1.0) lib/valkyrie/persistence/custom_query_container.rb:55:in `block (2 levels) in register_query_handler'
/app/samvera/hyrax-engine/app/models/hyrax/access_control.rb:39:in `for'
/app/samvera/hyrax-engine/app/services/hyrax/access_control_list.rb:254:in `access_control_model'
/app/samvera/hyrax-engine/app/services/hyrax/access_control_list.rb:260:in `change_set'
/app/samvera/hyrax-engine/app/services/hyrax/access_control_list.rb:184:in `destroy'
/app/samvera/hyrax-engine/lib/hyrax/transactions/steps/delete_access_control.rb:25:in `call'
/app/samvera/hyrax-engine/lib/hyrax/transactions/transaction.rb:99:in `block in call'
/app/samvera/hyrax-engine/lib/hyrax/transactions/transaction.rb:97:in `each'
/app/samvera/hyrax-engine/lib/hyrax/transactions/transaction.rb:97:in `inject'
/app/samvera/hyrax-engine/lib/hyrax/transactions/transaction.rb:97:in `call'
dry-monads (1.6.0) lib/dry/monads/do.rb:131:in `block in call'
dry-monads (1.6.0) lib/dry/monads/do/mixin.rb:40:in `call'
dry-monads (1.6.0) lib/dry/monads/do.rb:131:in `call'
/app/samvera/hyrax-engine/app/controllers/concerns/hyrax/works_controller_behavior.rb:118:in `destroy' 
```

### Acceptance Criteria/Expected Behavior

- [ ] Deleting a work succeeds without errors

### Related work

#6331

**Comment by rjkati** [comment]
works can be deleted in sirenia as an admin user and regular user
